<?php
define('ROOT_PATH', dirname(dirname(__DIR__)));
    define('VENDOR_PATH', ROOT_PATH.DIRECTORY_SEPARATOR.'vendor');
    define('TMP_PATH', ROOT_PATH.DIRECTORY_SEPARATOR.'tmp');
    define('SRC_PATH', ROOT_PATH.DIRECTORY_SEPARATOR.'src');
    define('TESTS_PATH', ROOT_PATH.DIRECTORY_SEPARATOR.'tests');
    define('ASSETS_PATH', ROOT_PATH.DIRECTORY_SEPARATOR.'assets');
        define('ASSETS_ENCORE_CONFIG_PATH', ASSETS_PATH.DIRECTORY_SEPARATOR.'config');
    define('PUBLIC_PATH', ROOT_PATH.DIRECTORY_SEPARATOR.'www');
        define('ENCORE_BUILD_PATH', PUBLIC_PATH.DIRECTORY_SEPARATOR.'static');
